config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  resources :boards do 
    resources :lists
  end 

  resources :lists do 
    resources :tasks
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists, dependent: :destroy

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
  
  # , before_add: :set_nest

  # private 
  #   def set_nest(tasks)

  #   end 
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show,:edit, :update, :destroy]
  def index
    @boards = Board.all
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path
    else 
      render :new
    end 
  end 

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else 
      render :edit
    end 
  end 

  def destroy
    @board.destroy
    redirect_to boards_path
  end 

  private

  def set_board
    @board = Board.find(params[:id])
  end 

  def board_params
    params.require(:board).permit(:title)
  end 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show,:update, :edit, :destroy]
  
  def index
    @lists = @board.lists
   
  end

  def show
  end

  def new
    @list = @board.lists.new
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
    redirect_to board_lists_path(@board)
    else
    render :new
    end 
  end 

  def edit
  end
  
  def update
    
    if @list.update(list_params)
      redirect_to board_lists_path(@board)
    else 
      render :edit
    end 
  end 

  def destroy
    @list.destroy
    redirect_to board_lists_path(@board)
  end 

  private

  def set_board
    @board = Board.find(params[:board_id])
  end 

  def set_list
    @list = @board.lists.find(params[:id])
  end 

  def list_params
    params.require(:list).permit(:name)
  end 

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:show,:update, :edit, :destroy]

  def index
    @tasks = @list.tasks
  end

  def show
  end

  def new
    @task = @list.tasks.new
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
    redirect_to list_tasks_path(@list)
    else
    render :new
    end 
  end 

  def edit
  end
  
  def update
    
    if @task.update(task_params)
      redirect_to list_tasks_path(@list)
    else 
      render :edit
    end 
  end 

  def destroy
    @task.destroy
    redirect_to list_tasks_path(@list)
  end 

  private

  def set_list
    @list = List.find(params[:list_id])
  end 

  def set_task
    @task = @list.tasks.find(params[:id])
  end 

  def task_params
    params.require(:task).permit(:name, :description,:priority, :list_id)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "form-group") do |f| %>

    <%= f.label :title%>
    <%= f.text_field :title %>
    <br/>
    <%= f.submit nil, class:"btn btn-primary"%>
    
<% end %>

app/views/boards/edit.html.erb
<h1><%="Edit #{@board.title}"%></h1>
<%= render partial: "form" %>

app/views/boards/index.html.erb
<h1>Choose From Your Boards</h1>
<div href="#" class="btn btn-outline-dark"><%= link_to "Add Board", new_board_path%></div>

<% @boards.each do |board|%>
<div class="board_div">
    <div class="card w-75">
    <div class="card-body">
        <h2 class="card-title"><%= link_to board.title, board_lists_path(board) %></h2>
        <div href="#" class="btn btn-outline-dark"><%= link_to "Edit", edit_board_path(board)%></div>
        <div href="#" class="btn btn-outline-dark"><%= link_to "Delete", board, method: :delete %></li></div>
    </div>
    </div>
</div>
<%end%>

app/views/boards/new.html.erb
<h1>New Board</h1>
<%=render partial: "form" %>

app/views/boards/show.html.erb
<h1>Boards#show</h1>
<p>Find me in app/views/boards/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Trello</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <div><%=link_to "Add Board", new_board_path, class:"nav-link"%><div>
      </li>
 
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <link href="https://fonts.googleapis.com/css?family=Assistant&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
  <img src="/backphoto.jpg" class="background_pic" width="100%" height="100%">
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [@board, @list], local: true, class: "form-group") do |f| %>

<%= f.label :name%>
<%= f.text_field :name %>
<br/>
<%= f.submit nil, class:"btn btn-primary"%>

<% end %>

app/views/lists/edit.html.erb
<h1><%="Edit #{@list.name}"%></h1>
<%= render partial: "form" %>

app/views/lists/index.html.erb
<h1><%= @board.title%></h1>

<div href="#" class="btn btn-outline-dark"><%= link_to "Add List", new_board_list_path(@board)%></div>
<div href="#" class="btn btn-outline-dark"><%= link_to "Back to Your Boards", boards_path%></div>
<hr>

<div class="list-flex">
<% @board.lists.each do |list|%>
<div class="margin">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h3 class="card-title"><%= list.name%></h3>
    <div href="#" class="btn btn-outline-dark"><%= link_to "Edit", edit_board_list_path(@board, list)%></div>
    <div href="#" class="btn btn-outline-dark"><%= link_to "Delete", board_list_path(@board, list), method: :delete %></div>
    <div href="#" class="btn btn-outline-dark"><%= link_to "Add task", new_list_task_path(list)%></div>
  </div>
  <% list.tasks.each do |task|%>
  <div class="margin_2">
  <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
  <div class="card-header">Priority: <%= task.priority%></div>
  <div class="card-body">
    <h5 class="card-title"><%= task.name%></h5>
    <p class="card-text"><%= task.description%></p>
  </div>
      <div class="button_flex">
        <div href="#" class="btn btn-outline-dark"><%= link_to "Edit", edit_list_task_path(list, task)%></div>
        <div href="#" class="btn btn-outline-dark"><%= link_to "Delete", [list, task],  method: :delete %></div>
      </div>
    </div>
  </div>
  <%end%>
  </div>
  </div>
<%end %>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= render partial: "form"%>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/tasks/_form.html.erb
<%= form_with(model: [@list, @task], local: true, class: "form-group") do |f| %>

<%= f.label :name%>
<%= f.text_field :name %>
<br/>
<%= f.label :description%>
<%= f.text_area :description %>
<br/>
<%= f.label :priority %>
<%= f.number_field :priority %>
<br/>
<%= f.label :list_id %>
<%= f.number_field :list_id %>
<br/>
<%= f.submit nil, class:"btn btn-primary"%>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%=render partial: "form"%>

app/views/tasks/index.html.erb
<h1>All of Your Tasks for <%="#{@list.name}"%> </h1>
<% @tasks.each do |task|%>
  <div class="margin_2">
  <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
  <div class="card-header">Priority: <%= task.priority%></div>
  <div class="card-body">
    <h5 class="card-title"><%= task.name%></h5>
    <p class="card-text"><%= task.description%></p>
  </div>
      
    </div>
  </div>
  <%end%>

<div href="#" class="btn btn-secondary"><%= link_to "Back to Boards", root_path%></div>

app/views/tasks/new.html.erb
<h1>New Tasks</h1>

<%=render partial: "form"%>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>